In [37]:
import pandas as pd
import numpy as np
import feather
%matplotlib inline

### Part I. Get the StopID location from googletransit data

In [38]:
# Read and prepare data
stops = pd.read_csv('./googletransit20121129-1547/stops.csv')
stops['StopID'] = stops['stop_id'].str[-4:]
stops = stops.rename(columns = {'stop_lat':'Lat'})
stops = stops.rename(columns = {'stop_lon':'Lon'})
googletransit_stops = stops.loc[:,['StopID', 'Lat', 'Lon']]

### Part II. For those StopID not in googletransit, use the maximun occurance in gps data as its location

In [39]:
res = pd.read_feather('DBus_stage_two_clean_v4.feather')

In [40]:
# Get the StopID list in gps data
gb_gps_stops = res.groupby('StopID')
gb_gps_stops_c = gb_gps_stops.count()
gps_stops = gb_gps_stops_c.reset_index('StopID')
gps_stops = gps_stops.loc[:,['StopID', 'AtStop']]
gps_stops = gps_stops.rename(columns = {'AtStop':'Count'})
gps_stops

     StopID  Count
0      0010  65360
1      0100   8643
2      1000   5076
3      1001  14737
4      1002   7186
5      1003   5369
6      1004   4372
7      1005  10585
8      1006   3828
9      1007   7803
10     1008   5338
11     1009   7355
12     1010  16127
13     1012  67488
14     1013   7507
15     1014  73879
16     1015  89897
17     1016  64406
18     1017  42466
19     1018  29862
20     1019  33249
21     0102   5982
22     1020  51112
23     1021   5613
24     1022   6755
25     1023   4656
26     1024  21961
27     1035   5441
28     1036   3896
29     1037   3797
...     ...    ...
4729   0961   7712
4730   0962   7773
4731   0963   7301
4732   0964   8344
4733   0965  16391
4734   0966   6553
4735   0967   4878
4736   0968  12066
4737   0969    429
4738   0972  25564
4739   0973  14869
4740   0974   7114
4741   0975   6400
4742   0976  12382
4743   0979  17330
4744   0980   7695
4745   0981  22923
4746   0983  13550
4747   0984   6633
4748   0985  18364
4749   0987  12205
4750   0988   6974
4751   0989   5826
4752   0990   5626
4753   0991  19839
4754   0992  18443
4755   0993  25255
4756   0997   3567
4757   0998   4097
4758   0999   5496

[4759 rows x 2 columns]

In [41]:
# Compare stops in gps data and googletransit data
compare_stops = pd.merge(gps_stops, stops, on='StopID', how='outer')
compare_stops

,StopID,Count,stop_id,stop_name,Lat,Lon
0,0010,65360.0,8220DB000010,"Parnell Square, Rotunda",53.353383,-6.265389
1,0100,8643.0,8230DB000100,"Wellington Lane, Templeogue",53.303083,-6.322361
2,1000,5076.0,8220DB001000,"Oscar Traynor Rd, Coolock",53.390974,-6.201794
3,1001,14737.0,8220DB001001,"Oscar Traynor Rd, Coolock",53.390081,-6.199200
4,1002,7186.0,8220DB001002,"Tonlegee Rd, Coolock",53.389219,-6.195117
5,1003,5369.0,8220DB001003,"Tonlegee Rd, Coolock",53.390325,-6.190965
6,1004,4372.0,8220DB001004,"Tonlegee Rd, Edenmore",53.390719,-6.186107
7,1005,10585.0,8220DB001005,"Tonlegee Rd, Edenmore",53.390997,-6.181930
8,1006,3828.0,8220DB001006,"Tonlegee Rd, Edenmore",53.391170,-6.176811
9,1007,7803.0,8220DB001007,"Tonlegee Rd, Edenmore",53.391220,-6.172433
10,1008,5338.0,8220DB001008,"Kilbarrack Road, Donaghmede",53.391126,-6.166919
11,1009,7355.0,8220DB001009,"Kilbarrack Road, Donaghmede",53.391089,-6.164470
12,1010,16127.0,8220DB001010,"Kilbarrack Road, Howth Junction",53.390590,-6.158326
13,1012,67488.0,8240DB001012,"Kilbarrack Pde, Kilbarrack",53.390286,-6.152626
14,1013,7507.0,8220DB001013,"Earlsfort Tce, Dublin City South",53.335481,-6.257542
15,1014,73879.0,8220DB001014,"Earlsfort Tce, Dublin City South",53.335676,-6.257339
16,1015,89897.0,8220DB001015,"Adelaide Road, Dublin City South",53.332730,-6.259936
17,1016,64406.0,8220DB001016,"Richmond Street Sth, Portobello",53.331132,-6.264416
18,1017,42466.0,8220DB001017,"Rathmines Road, Rathmines",53.329369,-6.264322
19,1018,29862.0,8220DB001018,"Rathmines Road, Ranelagh",53.327567,-6.264635
20,1019,33249.0,8220DB001019,"Rathmines Road, Rathmines",53.326465,-6.264845
21,0102,5982.0,8220DB000102,"Balbutcher Lane, Ballymun",53.397764,-6.267705
22,1020,51112.0,8220DB001020,"Rathmines Road, Rathmines",53.325076,-6.265112
23,1021,5613.0,8220DB001021,"Rathmines Road, Rathmines",53.321371,-6.265637
24,1022,6755.0,8220DB001022,"Rathmines Road, Rathmines",53.319513,-6.264542
25,1023,4656.0,8220DB001023,"Rathmines Rd, Rathmines",53.317046,-6.264897
26,1024,21961.0,8220DB001024,"Rathmines Road, Rathmines",53.315852,-6.264991
27,1035,5441.0,8250DB001035,"Churchtown Rd, Churchtown",53.295104,-6.256111
28,1036,3896.0,8250DB001036,"Braemor Road, Churchtown",53.295812,-6.259052
29,1037,3797.0,8250DB001037,"Braemor Road, Churchtown",53.300800,-6.263395
...,...,...,...,...,...,...
4779,0972,25564.0,8220DB000972,"Oscar Traynor Rd, Kilmore",53.396996,-6.234909
4780,0973,14869.0,8220DB000973,"Coolock Lane, Santry",53.398198,-6.242694
4781,0974,7114.0,8220DB000974,"Santry Avenue, Santry",53.397839,-6.247010
4782,0975,6400.0,8220DB000975,"Santry Avenue, Santry",53.399308,-6.252784
4783,0976,12382.0,8220DB000976,"Santry Avenue, Santry",53.400947,-6.262884
4784,0979,17330.0,8220DB000979,"Seamus Ennis Rd, Glasnevin",53.389954,-6.297086
4785,0980,7695.0,8220DB000980,"Mellowes Rd, Finglas",53.389877,-6.303073
4786,0981,22923.0,8220DB000981,"Mellowes Rd, Finglas",53.389828,-6.306548
4787,0983,13550.0,8220DB000983,"Mellowes Rd, Finglas",53.390141,-6.310941
4788,0984,6633.0,8220DB000984,"Mellowes Rd, Finglas",53.389911,-6.306740
4789,0985,18364.0,8220DB000985,"Mellowes Rd, Finglas",53.389978,-6.303881
4790,0987,12205.0,8220DB000987,"Finglas Village, Glasnevin",53.390282,-6.299313
4791,0988,6974.0,8220DB000988,"Seamus Ennis Rd, Finglas",53.389898,-6.295690
4792,0989,5826.0,8240DB000989,"Santry Avenue, Santry",53.401042,-6.262594
4793,0990,5626.0,8220DB000990,"Santry Avenue, Santry",53.398891,-6.250696
4794,0991,19839.0,8220DB000991,"Santry Avenue, Santry",53.397705,-6.246444
4795,0992,18443.0,8240DB000992,"Coolock Lane, Santry",53.398149,-6.241192
4796,0993,25255.0,8220DB000993,"Oscar Traynor Rd, Kilmore",53.397693,-6.229211
4797,0997,3567.0,8220DB000997,"Oscar Traynor Rd, Coolock",53.394140,-6.211539
4798,0998,4097.0,8220DB000998,"Oscar Traynor Rd, Coolock",53.393575,-6.209774
4799,0999,5496.0,8220DB000999,"Oscar Traynor Rd, Coolock",53.392241,-6.205965
4800,0260,NaN,8220DB000260,"Parnell Square East, Dublin",53.354285,-6.263114
4801,4338,NaN,8220DB004338,"St Patrick's Close, Dublin City South",53.339317,-6.271592
4802,7244,NaN,8220DB007244,"Clongriffin Rd, Clongriffin",53.402873,-6.154577
4803,0001,NaN,8240VIR0001,"Virtual Stop 1, St. Margaret's",53.417999,-6.278498
4804,0766,NaN,8250DB000766,"UCD, Belfield",53.305394,-6.218357
4805,0622,NaN,8250VIR0622,"Virtual Stop 7 R108, St. Margaret's",53.420962,-6.297697
4806,0623,NaN,8250VIR0623,"Virtual Stop 8 R108, St. Margaret's",53.421656,-6.305418
4807,0652,NaN,8250VIR0652,"Yellow Walls Road, Dublin",53.452730,-6.173858
4808,0660,NaN,8250VIR0660,"College Street, Dublin",53.345383,-6.257949

In [42]:
# Get StopID not in googletransit
not_in_googletransit = compare_stops[compare_stops.Lat.isnull()]['StopID']

In [43]:
# Get the subset of whole rows that StopID is not in googletransit
res_no_LonLat_in_googletransit = res[res.StopID.isin(not_in_googletransit)]

In [44]:
# Start to find the Lon/Lat by using the max co-ordinate occurance in gps data
# Here mark off select AtStop == True is some StopID even only have no AtStop == True

res_no_LonLat_in_googletransit = res_no_LonLat_in_googletransit[res_no_LonLat_in_googletransit.AtStop == True]
res_no_LonLat_in_googletransit['Lat/Lon'] = res_no_LonLat_in_googletransit.loc[:,['Lat','Lon']].apply(lambda x: str(x[0]) + "," + str(x[1]), axis=1)

In [45]:
# Get the count of each occurance of Lat and Lon
gb = res_no_LonLat_in_googletransit.groupby(['StopID', 'Lat/Lon'])
count = gb.count()
gb_count = count[count.AtStop > 0]
gb_count = gb_count.reset_index(['StopID', 'Lat/Lon'])
gb_count = gb_count.loc[:,['StopID', 'Lat/Lon','AtStop']]

In [46]:
# Get the maximun occurance of Lat/Lon of each StopID
max_count = gb_count[gb_count.groupby(['StopID'])['AtStop'].transform('max') == gb_count['AtStop']]

In [47]:
# Separate Lat/Lon to Lat and Lon
max_count['Lat'] = max_count['Lat/Lon'].apply(lambda x: x[:x.index(',')])
max_count['Lon'] = max_count['Lat/Lon'].apply(lambda x: x[x.index(',')+1:])

/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [48]:
# Change the data type first
max_count['Lat'] = max_count['Lat'].convert_objects(convert_numeric=True)
max_count['Lon'] = max_count['Lon'].convert_objects(convert_numeric=True)

/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [49]:
gb = max_count.groupby('StopID').mean()
stopID_lat_lon = gb[gb.AtStop>0]
stopID_lat_lon = stopID_lat_lon.reset_index('StopID')
gps_stops = stopID_lat_lon.loc[:,['StopID', 'Lat', 'Lon']]

In [50]:
# For those only exists AtStop == False


all_require_stops = set(not_in_googletransit)
calaulated_stops = set(gps_stops.StopID.unique())

need_to_calculate = all_require_stops - calaulated_stops
need_to_calculate

{'0920',
 '0921',
 '0922',
 '0932',
 '0954',
 '0955',
 '7485',
 '7497',
 '7503',
 '7504',
 '7541'}

In [51]:
res_no_LonLat_in_googletransit_2 = res[res.StopID.isin(need_to_calculate)]
res_no_LonLat_in_googletransit_2

,level_0,index,AtStop,Day,Delay,JourneyPatternID,Lat,Lon,Route,StopID,TimeFrame,Timestamp,VehicleID,VehicleJourneyID,DateTime,Rain_Avg,Wind_Speed_Avg,SchoolHoliday
57227138,57227138,737411,False,Wednesday,-504,00390002,53.394142,-6.391830,0039,7497,2013-01-30,2013-01-30 23:58:25,36060,3256,2013-01-30 23,0.000000,15.5,False
57227139,57227139,737412,False,Saturday,73,00390002,53.394196,-6.391732,0039,7497,2013-01-26,2013-01-27 00:02:42,36059,10172,2013-01-27 00,0.533333,23.0,True
57227140,57227140,737413,False,Friday,-406,00390002,53.394341,-6.391468,0039,7497,2013-01-25,2013-01-25 23:59:49,36059,3256,2013-01-25 23,0.000000,18.0,False
57227141,57227141,737414,False,Thursday,58,00390002,53.394142,-6.391830,0039,7497,2013-01-24,2013-01-25 00:07:49,36069,3256,2013-01-25 00,0.000000,11.5,False
57227142,57227142,737415,False,Wednesday,-262,00390002,53.394398,-6.391368,0039,7497,2013-01-23,2013-01-24 00:02:05,36060,3256,2013-01-24 00,0.000000,5.0,False
57227143,57227143,737416,False,Tuesday,-442,00390002,53.394073,-6.391952,0039,7497,2013-01-22,2013-01-22 23:59:23,36060,3256,2013-01-22 23,0.000000,3.0,False
57227144,57227144,737417,False,Saturday,222,00390002,53.394123,-6.391864,0039,7497,2013-01-19,2013-01-20 00:05:27,33558,10172,2013-01-20 00,0.000000,9.0,True
57227145,57227145,737418,False,Friday,-122,00390002,53.394264,-6.391611,0039,7497,2013-01-18,2013-01-19 00:04:22,36066,3256,2013-01-19 00,0.200000,10.0,False
57227146,57227146,737419,False,Thursday,-475,00390002,53.394073,-6.391952,0039,7497,2013-01-17,2013-01-17 23:58:45,36049,3256,2013-01-17 23,0.100000,19.0,False
57227147,57227147,737420,False,Thursday,-454,00390002,53.394073,-6.391952,0039,7497,2013-01-17,2013-01-17 23:59:03,36049,3256,2013-01-17 23,0.100000,19.0,False
57227148,57227148,737421,False,Thursday,-454,00390002,53.394073,-6.391952,0039,7497,2013-01-17,2013-01-17 23:59:50,36049,3256,2013-01-17 23,0.100000,19.0,False
57227149,57227149,737422,False,Wednesday,-465,00390002,53.394123,-6.391864,0039,7497,2013-01-16,2013-01-16 23:58:49,36067,3256,2013-01-16 23,0.066667,12.0,False
57227150,57227150,737423,False,Tuesday,-427,00390002,53.394440,-6.391290,0039,7497,2013-01-15,2013-01-15 23:59:26,36049,3256,2013-01-15 23,0.000000,5.0,False
57227151,57227151,737424,False,Monday,-587,00390002,53.394146,-6.391819,0039,7497,2013-01-14,2013-01-14 23:56:43,36053,3256,2013-01-14 23,0.000000,10.0,False
57227152,57227152,737425,False,Friday,243,00390002,53.394073,-6.391952,0039,7497,2013-01-11,2013-01-12 00:10:47,36070,3256,2013-01-12 00,0.166667,5.5,False
57227153,57227153,737426,False,Thursday,-481,00390002,53.394073,-6.391952,0039,7497,2013-01-10,2013-01-10 23:58:28,36051,3256,2013-01-10 23,0.000000,9.0,False
57227154,57227154,737427,False,Wednesday,-760,00390002,53.394073,-6.391952,0039,7497,2013-01-09,2013-01-09 23:53:46,36047,3256,2013-01-09 23,0.000000,6.0,False
57227155,57227155,737428,False,Sunday,241,00390002,53.394402,-6.391357,0039,7497,2013-01-06,2013-01-06 23:58:25,40005,14778,2013-01-06 23,0.000000,10.5,True
57227156,57227156,737429,False,Friday,-587,00390002,53.394299,-6.391545,0039,7497,2013-01-04,2013-01-04 23:56:47,36047,3256,2013-01-04 23,0.000000,4.5,True
57227157,57227157,737430,False,Thursday,-356,00390002,53.394398,-6.391368,0039,7497,2013-01-03,2013-01-04 00:00:31,36070,3256,2013-01-04 00,0.000000,12.5,True
57227158,57227158,737431,False,Wednesday,-495,00390002,53.394371,-6.391413,0039,7497,2013-01-02,2013-01-02 23:58:22,33593,3256,2013-01-02 23,0.000000,14.0,True
57227159,57227159,737432,False,Thursday,-524,00390002,53.394188,-6.391743,0039,7497,2012-11-29,2012-11-29 23:57:51,36064,3327,2012-11-29 23,0.000000,4.5,False
57227160,57227160,737433,False,Wednesday,-500,00390002,53.394398,-6.391368,0039,7497,2012-11-21,2012-11-21 23:58:09,36053,3288,2012-11-21 23,0.033333,13.0,False
57227161,57227161,737434,False,Tuesday,-556,00390002,53.394264,-6.391611,0039,7497,2012-11-20,2012-11-20 23:57:12,36048,3288,2012-11-20 23,0.000000,10.0,False
57227162,57227162,737435,False,Saturday,346,00390002,53.394238,-6.391655,0039,7497,2012-11-17,2012-11-18 00:07:22,33381,10837,2012-11-18 00,0.000000,11.0,True
57227163,57227163,737436,False,Wednesday,-204,00390002,53.394146,-6.391819,0039,7497,2012-11-14,2012-11-15 00:03:14,36059,3810,2012-11-15 00,0.000000,4.0,False
57227164,57227164,737437,False,Sunday,148,00390002,53.394196,-6.391732,0039,7497,2012-11-11,2012-11-11 23:57:00,40005,15381,2012-11-11 23,0.133333,5.5,True
57227165,57227165,737438,False,Friday,677,00390002,53.394073,-6.391952,0039,7497,2012-11-09,2012-11-10 00:18:02,36046,3810,2012-11-10 00,0.000000,11.5,False
57227166,57227166,737439,False,Tuesday,-269,00390002,53.394367,-6.391424,0039,7497,2012-11-06,2012-11-07 00:02:03,36062,3810,2012-11-07 00,0.000000,16.0,False
59836841,59836841,3347833,False,Wednesday,44,083A0001,53.421253,-6.306695,083A,7503,2013-01-30,2013-01-30 22:45:31,38072,5687,2013-01-30 22,0.000000,14.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70267932,70267932,13790647,False,Tuesday,41,027B1001,53.418915,-6.260349,027B,7485,2012-11-06,2012-11-06 14:52:39,33453,0287,2012-11-06 14,0.000000,17.0,False
70267933,70267933,13790648,False,Tuesday,39,027B1001,53.418953,-6.258527,027B,7485,2012-11-06,2012-11-06 15:12:43,33451,0329,2012-11-06 15,0.000000,16.5,False
70267934,70267934,13790649,False,Tuesday,20,027B1001,53.418583,-6.254194,027B,7485,2012-11-06,2012-11-06 15:13:01,33451,0329,2012-11-06 15,0.000000,16.5,False
70267935,70267935,13790650,False,Tuesday,18,027B1001,53.418861,-6.256563,027B,7485,2012-11-06,2012-11-06 15:32:46,33452,0346,2012-11-06 15,0.000000,16.5,False
70267936,70267936,13790651,False,Tuesday,497,027B1001,53.418934,-6.259854,027B,7485,2012-11-06,2012-11-06 16:00:34,33450,0281,2012-11-06 16,0.000000,15.5,False
70267937,70267937,13790652,False,Tuesday,497,027B1001,53.418880,-6.256741,027B,7485,2012-11-06,2012-11-06 16:00:54,33450,0281,2012-11-06 16,0.000000,15.5,False
70267938,70267938,13790653,False,Tuesday,497,027B1001,53.418583,-6.254194,027B,7485,2012-11-06,2012-11-06 16:01:14,33450,0281,2012-11-06 16,0.000000,15.5,False
70267939,70267939,13790654,False,Tuesday,-32,027B1001,53.418724,-6.255394,027B,7485,2012-11-06,2012-11-06 16:27:03,33276,0299,2012-11-06 16,0.000000,15.5,False
70267940,70267940,13790655,False,Tuesday,43,027B1001,53.418949,-6.258603,027B,7485,2012-11-06,2012-11-06 16:37:47,33496,0295,2012-11-06 16,0.000000,15.5,False
70267941,70267941,13790656,False,Tuesday,24,027B1001,53.418583,-6.254194,027B,7485,2012-11-06,2012-11-06 16:38:05,33496,0295,2012-11-06 16,0.000000,15.5,False
70267942,70267942,13790657,False,Tuesday,68,027B1001,53.418583,-6.254194,027B,7485,2012-11-06,2012-11-06 16:48:50,33453,0289,2012-11-06 16,0.000000,15.5,False
70267943,70267943,13790658,False,Tuesday,152,027B1001,53.418835,-6.256326,027B,7485,2012-11-06,2012-11-06 17:19:54,33451,0331,2012-11-06 17,0.000000,14.0,False
70267944,70267944,13790659,False,Tuesday,253,027B1001,53.418812,-6.256148,027B,7485,2012-11-06,2012-11-06 17:41:35,33452,0348,2012-11-06 17,0.000000,14.0,False
70267945,70267945,13790660,False,Tuesday,452,027B1001,53.418865,-6.260671,027B,7485,2012-11-06,2012-11-06 18:24:43,33450,0283,2012-11-06 18,0.000000,14.0,False
70267946,70267946,13790661,False,Tuesday,452,027B1001,53.418839,-6.256356,027B,7485,2012-11-06,2012-11-06 18:25:01,33450,0283,2012-11-06 18,0.000000,14.0,False
70267947,70267947,13790662,False,Tuesday,43,027B1001,53.418938,-6.257443,027B,7485,2012-11-06,2012-11-06 18:48:05,33496,0297,2012-11-06 18,0.000000,14.0,False
70267948,70267948,13790663,False,Tuesday,705,027B1001,53.418926,-6.260261,027B,7485,2012-11-06,2012-11-06 19:43:47,33451,0333,2012-11-06 19,0.000000,16.0,False
70267949,70267949,13790664,False,Tuesday,705,027B1001,53.418926,-6.260261,027B,7485,2012-11-06,2012-11-06 19:44:00,33451,0333,2012-11-06 19,0.000000,16.0,False
70267950,70267950,13790665,False,Tuesday,705,027B1001,53.418926,-6.260261,027B,7485,2012-11-06,2012-11-06 19:44:04,33451,0333,2012-11-06 19,0.000000,16.0,False
70267951,70267951,13790666,False,Tuesday,705,027B1001,53.418926,-6.260261,027B,7485,2012-11-06,2012-11-06 19:44:24,33451,0333,2012-11-06 19,0.000000,16.0,False
70267952,70267952,13790667,False,Tuesday,705,027B1001,53.417999,-6.274317,027B,7485,2012-11-06,2012-11-06 19:44:26,33451,0333,2012-11-06 19,0.000000,16.0,False
70267953,70267953,13790668,False,Tuesday,705,027B1001,53.417149,-6.266433,027B,7485,2012-11-06,2012-11-06 19:44:42,33451,0333,2012-11-06 19,0.000000,16.0,False
70267954,70267954,13790669,False,Tuesday,59,027B1001,53.418941,-6.259447,027B,7485,2012-11-06,2012-11-06 20:03:09,33453,0303,2012-11-06 20,0.000000,15.0,False
70267955,70267955,13790670,False,Tuesday,59,027B1001,53.418606,-6.254386,027B,7485,2012-11-06,2012-11-06 20:03:27,33453,0303,2012-11-06 20,0.000000,15.0,False
70267956,70267956,13790671,False,Tuesday,97,027B1001,53.418827,-6.256267,027B,7485,2012-11-06,2012-11-06 20:39:09,33452,0291,2012-11-06 20,0.000000,15.0,False
70267957,70267957,13790672,False,Tuesday,-22,027B1001,53.418934,-6.259975,027B,7485,2012-11-06,2012-11-06 21:31:44,40027,0335,2012-11-06 21,0.000000,14.0,False
70267958,70267958,13790673,False,Tuesday,-22,027B1001,53.418640,-6.254668,027B,7485,2012-11-06,2012-11-06 21:32:03,40027,0335,2012-11-06 21,0.000000,14.0,False
70267959,70267959,13790674,False,Tuesday,-25,027B1001,53.418957,-6.258120,027B,7485,2012-11-06,2012-11-06 21:56:51,33453,0305,2012-11-06 21,0.000000,14.0,False
70267960,70267960,13790675,False,Tuesday,130,027B1001,53.418949,-6.258799,027B,7485,2012-11-06,2012-11-06 22:24:15,33452,0293,2012-11-06 22,0.000000,16.0,False
70267961,70267961,13790676,False,Tuesday,112,027B1001,53.418583,-6.254194,027B,7485,2012-11-06,2012-11-06 22:24:33,33452,0293,2012-11-06 22,0.000000,16.0,False

In [52]:
res_no_LonLat_in_googletransit_2['Lat/Lon'] = res_no_LonLat_in_googletransit_2.loc[:,['Lat','Lon']].apply(lambda x: str(x[0]) + "," + str(x[1]), axis=1)


# Get the count of each occurance of Lat and Lon
gb = res_no_LonLat_in_googletransit_2.groupby(['StopID', 'Lat/Lon'])
count = gb.count()
gb_count = count[count.AtStop > 0]
gb_count = gb_count.reset_index(['StopID', 'Lat/Lon'])
gb_count = gb_count.loc[:,['StopID', 'Lat/Lon','AtStop']]

# Get the maximun occurance of Lat/Lon of each StopID
max_count = gb_count[gb_count.groupby(['StopID'])['AtStop'].transform('max') == gb_count['AtStop']]

# Separate Lat/Lon to Lat and Lon
max_count['Lat'] = max_count['Lat/Lon'].apply(lambda x: x[:x.index(',')])
max_count['Lon'] = max_count['Lat/Lon'].apply(lambda x: x[x.index(',')+1:])

# Change the data type first
max_count['Lat'] = max_count['Lat'].convert_objects(convert_numeric=True)
max_count['Lon'] = max_count['Lon'].convert_objects(convert_numeric=True)


gb = max_count.groupby('StopID').mean()
stopID_lat_lon = gb[gb.AtStop>0]
stopID_lat_lon = stopID_lat_lon.reset_index('StopID')
gps_stops_2 = stopID_lat_lon.loc[:,['StopID', 'Lat', 'Lon']]

gps_stops_2

/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:19: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:20: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/Users/EmmaChang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

  StopID      Lat      Lon
0   7485  53.4186 -6.25419
1   7497  53.3941 -6.39195
2   7503  53.4204 -6.30685
3   7504  53.4183 -6.30691
4   7541  53.4546 -6.17676

In [55]:
# Concate all
stops = pd.concat([googletransit_stops, gps_stops, gps_stops_2], axis=0)

In [57]:
stops.to_csv('input1_StopID_LonLat.csv', index=False)